#!/bin/bash

# Settings for the Files
AUTHFILE=/var/log/tomcat7/localhost_access_log.$(date +%Y-%m-%d).txt
#echo $AUTHFILE
TMPBASE=/tmp
TMPGET=$TMPBASE/tomcat.tmp.get
TMPPOST=$TMPBASE/tomcat.tmp.post
TMPIPSGET=$TMPBASE/tomcat.tmp.ipsget
TMPIPSPOST=$TMPBASE/tomcat.tmp.ipspost
TMPIPSGETU=$TMPBASE/tomcat.getipsuniq
TMPIPSPOSTU=$TMPBASE/tomcat.postipsuniq
echo
# Clean up any existing tmp files
rm -f "$TMPPOST" "$TMPFAIL" "$TMPIPSGET" "$TMPIPSPOST" "$TMPIPSGETU" "$TMPIPSPOSTU"

# Get all Failed Authentication Lines
# Add sudo before grep if need be, such as on BSD system
grep '[Gg]ET' "$AUTHFILE" > "$TMPGET"

grep '[Pp]OST' "$AUTHFILE" > "$TMPPOST"

# Pull All the IPs out
egrep -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' "$TMPGET" > "$TMPIPSGET"

egrep -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' "$TMPPOST" > "$TMPIPSPOST"

# Sort out Unique IPs
sort -u "$TMPIPSGET" > "$TMPIPSGETU"

sort -u "$TMPIPSPOST" > "$TMPIPSPOSTU"

# Count attacks from individual IPs And Output Results
echo "ALL IPS THAT POST"
while read ip
do
    echo "$(grep -c "$ip" "$TMPIPSPOST") Posted => $ip" 
    pip=$ip
    #"From: $(lynx -dump http://www.ip-adress.com/ip_tracer/?QRY=$ip|grep address|egrep 'city|state|country'|awk '{print $3,$4,$5,$6,$7,$8}'|sed 's\ip address flag \\'|sed 's\My\\')" 
done < "$TMPIPSPOSTU" | sort -g
echo
echo "ALL IPS THAT GET"
while read ip
do
    echo "$(grep -c "$ip" "$TMPIPSGET") Getted => $ip"
done < "$TMPIPSGETU" | sort -g
echo
echo Total Unique IPs Getting: $(cat "$TMPIPSGETU" | wc -l)
echo Total Unique IPs Posting: $(cat "$TMPIPSPOSTU" | wc -l)
#echo "Total IPs Getting From Outside Network: `expr $(cat "$TMPIPSGET" | wc -l) - $(grep -c "$TMPIPSPOSTU" | less "$TMPIPSGET")`" 

